export const metricTranslations = {
  uk: { daily: "Дохід/день", rate: "Ставка", hour: "зл/год", order: "зл/зам", km: "зл/км", day: "зл/день" },
  pl: { daily: "Dochód/dzień", rate: "Stawka", hour: "zł/godz.", order: "zł/zam.", km: "zł/km", day: "zł/dzień" },
  en: { daily: "Income/day", rate: "Rate", hour: "PLN/hr", order: "PLN/order", km: "PLN/km", day: "PLN/day" },
  ru: { daily: "Доход/день", rate: "Ставка", hour: "зл/ч", order: "зл/зак.", km: "зл/км", day: "зл/день" },
}

export const comparisonTranslations = {
  uk: { share: "доходу", title: "Порівняння періодів", income: "Дохід", rate: "Ставка", unit: "PLN/год", recorded: "Порівняння лише за внесеними записами.", today: "Сьогоднішні записи не входять у порівняння. Періоди обмежені спільною кількістю завершених календарних днів.", loading: "Дані завантажуються.", error: "Не вдалося завантажити дані.", future: "Майбутній місяць ще не можна порівняти.", noDays: "Цього місяця ще немає завершених днів.", noRecords: "В одному з періодів немає записів для порівняння.", taxes: "NETTO недоступне: налаштуйте податки.", fixed: "NETTO недоступне: фіксовані платежі не розподіляються на неповний місяць або частину платформ.", hours: "Ставка недоступна: немає коректних годин для обох періодів або години спільні для кількох платформ.", base: "Попереднє значення не є додатним: немає коректної бази для відсоткового порівняння." },
  pl: { share: "dochodu", title: "Porównanie okresów", income: "Dochód", rate: "Stawka", unit: "PLN/godz.", recorded: "Porównanie obejmuje tylko zapisane zmiany.", today: "Dzisiejsze wpisy nie są uwzględnione. Okresy obejmują wspólną liczbę zakończonych dni kalendarzowych.", loading: "Ładowanie danych.", error: "Nie udało się wczytać danych.", future: "Przyszłego miesiąca nie można jeszcze porównać.", noDays: "W tym miesiącu nie ma jeszcze zakończonych dni.", noRecords: "Brak wpisów do porównania w jednym z okresów.", taxes: "NETTO niedostępne: skonfiguruj podatki.", fixed: "NETTO niedostępne: opłaty stałe nie są dzielone na część miesiąca lub platform.", hours: "Stawka niedostępna: brak poprawnych godzin dla obu okresów lub godziny są wspólne dla platform.", base: "Poprzednia wartość nie jest dodatnia: brak podstawy porównania procentowego." },
  en: { share: "of income", title: "Period comparison", income: "Income", rate: "Hourly rate", unit: "PLN/hour", recorded: "Comparison uses recorded shifts only.", today: "Today's records are excluded. Both periods use the same available number of completed calendar days.", loading: "Loading data.", error: "Could not load data.", future: "A future month cannot be compared yet.", noDays: "This month has no completed days yet.", noRecords: "One of the periods has no records to compare.", taxes: "NET income unavailable: configure taxes.", fixed: "NET income unavailable: fixed fees are not allocated to partial months or platform subsets.", hours: "Hourly rate unavailable: valid hours are missing for either period or shared between platforms.", base: "The previous value is not positive: no valid base for percentage comparison." },
  ru: { share: "дохода", title: "Сравнение периодов", income: "Доход", rate: "Ставка", unit: "PLN/час", recorded: "Сравнение только по внесённым записям.", today: "Сегодняшние записи не учитываются. Оба периода ограничены общим количеством завершённых календарных дней.", loading: "Данные загружаются.", error: "Не удалось загрузить данные.", future: "Будущий месяц пока нельзя сравнить.", noDays: "В этом месяце ещё нет завершённых дней.", noRecords: "В одном из периодов нет записей для сравнения.", taxes: "НЕТТО недоступно: настройте налоги.", fixed: "НЕТТО недоступно: фиксированные платежи не распределяются на часть месяца или платформ.", hours: "Ставка недоступна: нет корректных часов для обоих периодов или часы общие для платформ.", base: "Предыдущее значение не положительное: нет корректной базы процентного сравнения." },
}
