begin;

create extension if not exists "uuid-ossp"
  with schema extensions;

create table public.profiles (
  id uuid not null,
  nickname text,

  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey
    foreign key (id)
    references auth.users (id)
    on delete cascade,
  constraint profiles_nickname_key unique (nickname)
);

create table public.work_shifts (
  id bigint generated always as identity,
  date date not null,
  km numeric not null default 0,
  hours numeric not null default 0,
  uber numeric not null default 0,
  wolt numeric not null default 0,
  bolt numeric not null default 0,
  glovo numeric not null default 0,
  created_at timestamp with time zone not null
    default timezone('utc'::text, now()),
  user_id uuid not null,
  orders_uber integer default 0,
  orders_wolt integer default 0,
  orders_bolt integer default 0,
  orders_glovo integer default 0,
  tips numeric default 0,
  bonuses numeric default 0,
  tips_uber numeric default 0,
  tips_wolt numeric default 0,
  tips_bolt numeric default 0,
  tips_glovo numeric default 0,
  bonuses_uber numeric default 0,
  bonuses_wolt numeric default 0,
  bonuses_bolt numeric default 0,
  bonuses_glovo numeric default 0,

  constraint work_shifts_pkey primary key (id),
  constraint work_shifts_user_date_key unique (user_id, date),
  constraint work_shifts_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
    on delete cascade
);

create table public.tax_settings (
  id uuid not null default extensions.uuid_generate_v4(),
  user_id uuid not null,
  uber_type text default 'none'::text,
  uber_val numeric default 0,
  wolt_type text default 'none'::text,
  wolt_val numeric default 0,
  bolt_type text default 'none'::text,
  bolt_val numeric default 0,
  glovo_type text default 'none'::text,
  glovo_val numeric default 0,
  updated_at timestamp with time zone
    default timezone('utc'::text, now()),

  constraint tax_settings_pkey primary key (id),
  constraint tax_settings_user_id_key unique (user_id),
  constraint tax_settings_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
);

create table public.garage_rules (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  name text,
  interval_km numeric,
  last_change_km numeric default 0,
  user_id uuid,

  constraint garage_rules_pkey primary key (id),
  constraint garage_rules_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
    on delete cascade
);

create table public.garage_history (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  service_type text,
  name text,
  date date,
  cost numeric,
  rule_id numeric,
  odometer numeric,
  user_id uuid,

  constraint garage_history_pkey primary key (id),
  constraint garage_history_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
    on delete cascade
);

alter table public.profiles enable row level security;
alter table public.work_shifts enable row level security;
alter table public.tax_settings enable row level security;
alter table public.garage_rules enable row level security;
alter table public.garage_history enable row level security;

create policy "Профілі можуть читати всі"
  on public.profiles
  as permissive
  for select
  to public
  using (true);

create policy "Користувач може створювати свій п"
  on public.profiles
  as permissive
  for insert
  to public
  with check (auth.uid() = id);

create policy "Користувач може оновлювати свій п"
  on public.profiles
  as permissive
  for update
  to public
  using (auth.uid() = id);

create policy work_shifts_policy
  on public.work_shifts
  as permissive
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can view own tax settings"
  on public.tax_settings
  as permissive
  for select
  to public
  using (auth.uid() = user_id);

create policy "Users can insert own tax settings"
  on public.tax_settings
  as permissive
  for insert
  to public
  with check (auth.uid() = user_id);

create policy "Users can update own tax settings"
  on public.tax_settings
  as permissive
  for update
  to public
  using (auth.uid() = user_id);

create policy "Користувач керує своїм гаражем"
  on public.garage_rules
  as permissive
  for all
  to public
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Користувач керує своєю історією"
  on public.garage_history
  as permissive
  for all
  to public
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant
  select,
  insert,
  update,
  delete,
  truncate,
  references,
  trigger,
  maintain
on table
  public.profiles,
  public.work_shifts,
  public.tax_settings,
  public.garage_rules,
  public.garage_history
to anon, authenticated, service_role;

grant select, update, usage
on sequence
  public.work_shifts_id_seq,
  public.garage_rules_id_seq,
  public.garage_history_id_seq
to anon, authenticated, service_role;

commit;
